### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by StefaniaJ** [cawfree/react-native-rotary#1]
Hi, I followed the steps to install it and I have a problem. It says: 
./node_modules/react-native-rotary/index.js
SyntaxError: C:\Users\lenovo\Desktop\exam2019\node_modules\react-native-rotary\index.js: Unexpected token (93:12)

  91 |             );
  92 |           return (
> 93 |             <Animated.View
     |             ^
  94 |               key={index}
  95 |               style={{
  96 |                 opacity: scale,

Do I have to install something else?
Thank you!

**Comment by cawfree** [comment]
Hello!

It looks like your project might not be configured properly; it seems to be
failing at the beginning of the first JSX tag. Are you using this with
React Native Web?

**Comment by StefaniaJ** [comment]
yes

**Comment by cawfree** [comment]
Okay, that's no problem. You just need to tell Webpack that you want to compile `react-native-rotary` with Babel by updating the `include` path for the Babel plugin (as you start to use other dependencies, you'll find this is a pretty common step):

**<App>/config/webpack.config.dev.js**
*Look for the line with says "Process the application JS with Babel."

```javascript
// Process application JS with Babel.
// The preset includes JSX, Flow, and some ESnext features.
{
 test: /\.(js|mjs|jsx|ts|tsx)$/,
 include: [
    paths.appSrc,
    path.resolve(paths.appNodeModules, "@cawfree/react-native-collapsible-view"),
 ],
}
```

**Comment by StefaniaJ** [comment]
I'm sorry, I'm using react native app. is it a different?

**Comment by cawfree** [comment]
That's okay. What device are you running this on?

**Comment by StefaniaJ** [comment]
Laptop

**Comment by cawfree** [comment]
Okay, so when you run your app you want to see it load in a Web Browser? Just to check, how do you start your app? Are you doing something like:

```
npm run android # or yarn android
npm run web # or yarn web
npm run ios # or yarn ios
```

**Comment by StefaniaJ** [comment]
Yes, this is what I want  and I'm using npm start

**Comment by cawfree** [comment]
Okay, so provided you have made [these changes](https://github.com/cawfree/react-native-rotary/issues/1#issuecomment-564582539), stop the metro bundler (which you've ran using `npm start`) and then use `npm run web` to restart the bundler, this plugin should work as expected on `localhost:3000`. :)
